
-- Create teams table
CREATE TABLE public.teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    coach_name TEXT,
    founded_year INTEGER,
    stadium TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create players table
CREATE TABLE public.players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT REFERENCES public.teams(id),
    full_name TEXT NOT NULL,
    position TEXT NOT NULL CHECK (position IN ('GK', 'DF', 'MF', 'FW')),
    age INTEGER NOT NULL,
    nationality TEXT,
    appearances INTEGER DEFAULT 0,
    goals INTEGER DEFAULT 0,
    assists INTEGER DEFAULT 0,
    yellow_cards INTEGER DEFAULT 0,
    red_cards INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;

-- RLS Policies for teams
CREATE POLICY "Enable read access for authenticated users" ON public.teams
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Enable write access for admins and coaches" ON public.teams
    FOR ALL TO authenticated USING (
        public.has_role(auth.uid(), 'admin') OR 
        public.has_role(auth.uid(), 'coach')
    );

-- RLS Policies for players
CREATE POLICY "Enable read access for authenticated users" ON public.players
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Enable write access for admins and coaches" ON public.players
    FOR ALL TO authenticated USING (
        public.has_role(auth.uid(), 'admin') OR 
        public.has_role(auth.uid(), 'coach')
    );

-- Seed Data (Initial Mock Data)
INSERT INTO public.teams (id, name, coach_name, founded_year, stadium) VALUES
  (1, 'FC Thunder', 'Carlos Martinez', 1985, 'Thunder Arena'),
  (2, 'United Stars', 'John Williams', 1990, 'Star Stadium'),
  (3, 'Royal Eagles', 'Ahmed Hassan', 1978, 'Eagle Nest'),
  (4, 'City Wolves', 'Michael Brown', 2002, 'Wolf Den'),
  (5, 'Athletic Lions', 'David Chen', 1995, 'Lion''s Roar'),
  (6, 'Dynamo FC', 'Igor Petrov', 1988, 'Dynamo Park');

-- Reset sequence for teams so next insert works
SELECT setval('public.teams_id_seq', (SELECT MAX(id) FROM public.teams));

INSERT INTO public.players (team_id, full_name, position, age, nationality, appearances, goals, assists, yellow_cards, red_cards) VALUES
  (1, 'Marcus Johnson', 'FW', 26, 'England', 32, 18, 7, 3, 0),
  (1, 'Leo Garcia', 'MF', 24, 'Spain', 30, 5, 12, 5, 1),
  (1, 'James Wilson', 'DF', 28, 'England', 34, 2, 1, 8, 0),
  (1, 'Pedro Santos', 'GK', 31, 'Brazil', 34, 0, 0, 1, 0),
  (2, 'Alex Mueller', 'FW', 23, 'Germany', 28, 14, 5, 2, 0),
  (2, 'Ryan O''Connor', 'MF', 27, 'Ireland', 31, 8, 9, 4, 0),
  (3, 'Omar El-Sayed', 'FW', 25, 'Egypt', 29, 12, 6, 1, 0),
  (3, 'Yuki Tanaka', 'MF', 22, 'Japan', 26, 3, 11, 2, 0),
  (4, 'Luca Rossi', 'DF', 29, 'Italy', 33, 1, 2, 7, 1),
  (5, 'Kai Weber', 'GK', 26, 'Germany', 34, 0, 0, 0, 0);
