
-- Create matches table
CREATE TABLE public.matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    home_team_id BIGINT REFERENCES public.teams(id) NOT NULL,
    away_team_id BIGINT REFERENCES public.teams(id) NOT NULL,
    home_score INTEGER DEFAULT 0 NOT NULL,
    away_score INTEGER DEFAULT 0 NOT NULL,
    date_time TIMESTAMP WITH TIME ZONE NOT NULL,
    venue TEXT,
    status TEXT NOT NULL CHECK (status IN ('SCHEDULED', 'IN_PLAY', 'FINISHED')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Enable read access for authenticated users" ON public.matches
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Enable write access for admins, coaches, and referees" ON public.matches
    FOR ALL TO authenticated USING (
        public.has_role(auth.uid(), 'admin') OR 
        public.has_role(auth.uid(), 'coach') OR
        public.has_role(auth.uid(), 'referee')
    );

-- Seed Data
INSERT INTO public.matches (id, home_team_id, away_team_id, home_score, away_score, date_time, venue, status) VALUES
  (1, 1, 2, 2, 1, '2025-12-10T19:00:00+00', 'Thunder Arena', 'SCHEDULED'),
  (2, 3, 4, 1, 1, '2025-12-08T15:30:00+00', 'Eagle Nest', 'IN_PLAY'),
  (3, 5, 6, 3, 0, '2025-12-07T20:00:00+00', 'Lion''s Roar', 'FINISHED'),
  (4, 2, 3, 0, 2, '2025-12-05T18:00:00+00', 'Star Stadium', 'FINISHED'),
  (5, 4, 1, 1, 3, '2025-12-03T21:00:00+00', 'Wolf Den', 'FINISHED'),
  (6, 6, 5, 0, 0, '2025-12-15T17:00:00+00', 'Dynamo Park', 'SCHEDULED');

-- Reset sequence
SELECT setval('public.matches_id_seq', (SELECT MAX(id) FROM public.matches));
